### ISSUE TITLE
Page update

### ISSUE THREAD

**Issue by Glavo** [dlang-tour/chinese#8]
@wilzbach Why was the github repo we provided updated while the page at https://tour.dlang.org/tour/zh/welcome/welcome-to-d was not?

**Comment by wilzbach** [comment]
@Glavo unfortunately our auto-deploy is temporarily disabled due to some weird issues with Docker and CentOS. (@stonemaster knows more details).

While we are debugging this, feel free to ping us any time for manual deploys. Sorry for the temporary inconvenience.

**Comment by Glavo** [comment]
thanks
